version: "3.2"
services:
  nodejs:
    build:
      context: .
    restart: unless-stopped
    depends_on:
      - mysql
    ports:
      - 8000:8000  
    environment:
      - DB_HOST=localhost
      - DB_PASSWORD=root
      - DB_NAME=users
      - DB_USER=root
      - DB_PORT=3000  
    tty: true
  mysql:
    image: mysql:5.7
    environment:
      - DB_HOST=localhost
      - DB_PASSWORD=root
      - DB_NAME=users
      - DB_USER=root
      - DB_PORT=3000
    restart: unless-stopped
    ports:
      - '3000:3000'